// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx53L2y1dbhuIP__-t_2t02sThtjnn1f4',
    appId: '1:507471318000:web:8b1678588eee1e53e96b35',
    messagingSenderId: '507471318000',
    projectId: 'openledger-1',
    authDomain: 'openledger-1.firebaseapp.com',
    storageBucket: 'openledger-1.firebasestorage.app',
    measurementId: 'G-EBVBQ6X903',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJzagIdNv2shMCIfp77DbmNr08F3YaXk',
    appId: '1:507471318000:android:2c68c94a24def9e3e96b35',
    messagingSenderId: '507471318000',
    projectId: 'openledger-1',
    storageBucket: 'openledger-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJz-4OT2YIBjrFVI978V50jt4gP5Yb3vw',
    appId: '1:507471318000:ios:38ae66432a888359e96b35',
    messagingSenderId: '507471318000',
    projectId: 'openledger-1',
    storageBucket: 'openledger-1.firebasestorage.app',
    iosBundleId: 'com.openledger.openLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJz-4OT2YIBjrFVI978V50jt4gP5Yb3vw',
    appId: '1:507471318000:ios:38ae66432a888359e96b35',
    messagingSenderId: '507471318000',
    projectId: 'openledger-1',
    storageBucket: 'openledger-1.firebasestorage.app',
    iosBundleId: 'com.openledger.openLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx53L2y1dbhuIP__-t_2t02sThtjnn1f4',
    appId: '1:507471318000:web:0fe1925c4da2dd6de96b35',
    messagingSenderId: '507471318000',
    projectId: 'openledger-1',
    authDomain: 'openledger-1.firebaseapp.com',
    storageBucket: 'openledger-1.firebasestorage.app',
    measurementId: 'G-0598SX6M54',
  );
}
